Hello fellow java package maintainer <PACKAGER_NAME>!

<TITLE>


I had run last kopr mass rebuild for JDK from java-11-openjdk to java-17-openjdk for f36. Please see https://fedoraproject.org/wiki/Changes/Java17.
Full report is: https://github.com/judovana/FedoraSystemJdkBump/blob/main/scritps/spammer...
Diff against rerun II: https://github.com/judovana/FedoraSystemJdkBump/commit/671d5aa1c1e7355f13...
There is still some ~70 failures.
This was the last rebuild in copr. Next week or two, I will do my best to run the mass rebuild in Koji, FTBFS will be filled, and unless it goes terribly wrong, the side tag will be merged, and all would be settled.

Thanx a lot to everybody who helped to fix the failures. It was some work, and is highly appreciated.
Also common issues grown a bit; https://fedoraproject.org/wiki/Changes/Java17#common_issues_packagers_can...

  J.

Old long Story and how to debug:

Short Story:
 * according to the package database, you (co)maintain at least <ITS_PKG_COUNT> java packages, be aware that we are bumping JDK in rawhide
 * Ensure your package builds and runs fine with <JDK_TO> (see the <COPR_URL> )
 * there is special tooling ready for this, before the mass rebuild is launched
 ** See <PROPOSAL_URL>#<PRELIMINARY_INFO>
 * If you do not want Fedora to rot with <JDK_FROM> for ever, continue reading

<LONG_STORY>

From those you (co)own following: <ITS_PKGS_LIST>

If some of your packages are missing here, and you think thwy should be included, don't hesitate to email/ping me or the mailing lists(devel or users @lists.fedoraproject.org). It could happen you have some very indirect requires or you require namely <JDK_FROM>(-devel). In that case yo should bump it according to packaging guidelines to java(-devel), verify you run against <JDK_TO> in my copr. Feel free to ask me to include such an package in my copr. I will gladly do so.

<<ALL_PASSED_START>>
Your summary is:
<ITS_PASSED> passed
<ITS_BORKED> even srpm failed - are missing, delete, retired or somehow else utterly missing in action (see lower)
<ITS_MISSING> found, but missingin in copr?
<ITS_FAILED> failed, from those <ITS_QUICK> failed very quickly (see lower)

Details:
* Passed: <ITS_PASSED_LIST>
* Missing: <ITS_BORKED_LIST>
  is/are probably orphan dead or really borked. If it is intentional, you may ignore it. If it is error, you  should resurrect the package and if in that, ensure it runs against <JDK_TO> (see failed)
* no-copr: <ITS_MISSING_LIST>
  is/are probably orphan dead or really borked. If it is intentional, you may ignore it. If it is error, you  should resurrect the package and if in that, ensure it runs against <JDK_TO> (see failed)
* Failed, suspiciously quickly: <ITS_QUICK_LIST>
those packages failed so quickly, that the build was in initial phases. That usually mean that you build with source/target lower then  <MIN_BYTECODE> <JDK_TO> supports  <MIN_BYTECODE> and up. We recommend to bump the source/target to <RECOMEND_BYTECODE>, to allow existence of compact <RECOMEND_BYTECODE> packages alongside main javastack. See <PROPOSAL_URL>#<WRONG_SOURCETARGETRELEASE>. Don't forget to upstream the patch, or maybe it is enough to update to more fresh upstream release which supports <JDK_TO>? it may happen, that after the fix, your build will fail in more terrible way (see bellow)
* Failed: <ITS_FAILED_SLOW_LIST>
those packages failed. Very often the scary error may be fixed by bump to latest upstream version. <JDK_TO> is out shortly, but changes against <JDK_FROM> are minimal, and upstreams keep an track. Please, try to fix the package. Don't hesitate to ask on devel@fedoraproject.org or java-devel@fedoraproject.org or directly to me <FROM_MAIL>. If you fix the fail, feel free to share your fix, it may help others. 
We are trying to gather the most common issues at <PROPOSAL_URL>#<COMMON_ISSUES> .  Feel free to enhance the page, or write us your case (possibly both with solution and without) so we can add it here. 
<<ALL_PASSED_END>>
----------
<DEBUGGING>

Thank You!
  J.

Those should be links to build logs:
<LATEST_STATUSES_WITH_LOGS>
MISSING:  <ITS_BORKED_LIST>

Links to all your known java packages:
<FEDORA_REPOS>

--
Jiri Vanek
jvanek@redhat.com
+420 775 39 01 09

