#!/usr/bin/python3
  # Stolen from:
  #  https://pagure.io/user/churchyard/projects -> https://pagure.io/fedora-misc-package-utilities
  # -> https://pagure.io/fedora-misc-package-utilities/raw/master/f/find-orphaned-packages
  # -> https://pagure.io/fedora-misc-package-utilities/raw/master/f/find-package-maintainers
  # the find-orphaned-packages have weird requires, so using find-package-maintainers
import argparse
import requests
import sys

def options_parse():
    p = argparse.ArgumentParser(
        description='Find maintainers given package names')

    p.add_argument('infile', type=argparse.FileType('r'),
                   nargs='?', default=sys.stdin,
                   help='file containing package names')
    p.add_argument('-v', '--verbose', action='store_true',
                   help='Be verbose')

    opts = p.parse_args()

    return opts

def main():
    opts = options_parse()

    packages = [line.strip() for line in opts.infile]
    owners = requests.get('https://src.fedoraproject.org/extras/pagure_owner_alias.json').json()

    by_package = {pkg: owners["rpms"][pkg] for pkg in packages}
    by_maintainer = {}

    print('Maintainers by package:')
    for pkg, maints in sorted(by_package.items()):
        print('{:20} {}'.format(pkg, ' '.join(sorted(maints))))

        for maint in maints:
            by_maintainer.setdefault(maint, []).append(pkg)

    print()
    print('Packages by maintainer:')
    for maint, pkgs in sorted(by_maintainer.items()):
        print('{:10} {}'.format(maint, ' '.join(pkgs)))

if __name__ == '__main__':
    main()
