package org.judovana.fedorajdkbump;

    import java.util.Date;
    import javax.mail.*;
    import javax.mail.internet.*;    

    public class Main {

        public static void main(String[] args) throws Exception {
            System.err.println("Current spammer is configured to run with OAuth 2.0 secured gmail");
            System.err.println("If you need to use different email server or different authentification, you have to go with new implementation");
            System.err.println("In addition, it is set to ssl/tls. If you need different, you have to modify this impl");
            System.err.println("WARNING. The OAuth token is temporary! Be sure you send all the emails before it expires (some hour or so)");
            System.err.println(" <email> <oauthToken>  template? list_of_owners? list_of_statuses?");
            System.err.println(" * template?  the body of email which will be processed and send to every owner of packages");
            System.err.println(" * list_of_owners?  list of all packages we care about, wiht owneres. generated by find-package-maintainers with depndent-packages.jbump as input. Eg maintainers.jbump");
            System.err.println(" * list_of_statuses?  copypasted table from your copr builds, with  buildId/pkg/vr/submitted/duration/status.like.failed|passed");
            System.err.println("Trying to spam through  ...");
            if (args.length != 2) {
                System.err.println("Usage: OAuth2Authenticator <email> <oauthToken>  template? list_of_owners? list_of_statuses?");
                System.err.println("eg: jvanek@rh.com ya29.a0...  some/file other/file copypasted/file");
                return;
            }
            Messagable messagable = com.google.code.samples.oauth2.OAuth2Authenticator.connect(args[0], args[1]);
            Message msg = new MimeMessage(messagable.getSession());
            msg.setFrom(new InternetAddress((args[0])));
            msg.setRecipients(Message.RecipientType.TO, InternetAddress.parse((args[0]), false));
            msg.setSubject("hello from gmial spammer "+System.currentTimeMillis());
            msg.setText("this is body of the fuure mesage for packagers");
            msg.setHeader("X-Mailer", "FedoraSystemJdkBump spamming program");
            msg.setSentDate(new Date());
            messagable.sendMessage(msg);
            messagable.sendMessage(msg);

        }

    }
